"""empty message

Revision ID: 561e1abeb163
Revises: cf6d7ebb8597
Create Date: 2019-02-25 14:51:48.598676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561e1abeb163'
down_revision = 'cf6d7ebb8597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('publish_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_date', sa.DATETIME(), nullable=False))
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
